const Alabama = require('./Alabama_occupation.json');
const Arkansas = require('./Arkansas_occupation.json');
const Arizona = require('./Arizona_occupation.json');
const Alaska = require('./Alaska_occupation.json');
const Colorado = require('./Colorado_occupation.json');
const Connecticut = require('./Connecticut_occupation.json');
const California = require('./California_occupation.json');
const Delaware = require('./Delaware_occupation.json');
const District_of_Columbia = require('./District_of_Columbia_occupation.json');
const Florida = require('./Florida_occupation.json');
const Georgia = require('./Georgia_occupation.json');
const Guam = require('./Guam_occupation.json');
const Hawaii = require('./Hawaii_occupation.json');
const Idaho = require('./Idaho_occupation.json');
const Illinois = require('./Illinois_occupation.json');
const Indiana = require('./Indiana_occupation.json');
const Iowa = require('./Iowa_occupation.json');
const Kansas = require('./Kansas_occupation.json');
const Kentucky = require('./Kentucky_occupation.json');
const Louisiana = require('./Louisiana_occupation.json');
const Maine = require('./Maine_occupation.json');
const Maryland = require('./Maryland_occupation.json');
const Massachusetts = require('./Massachusetts_occupation.json');
const Michigan = require('./Michigan_occupation.json');
const Minnesota = require('./Minnesota_occupation.json');
const Mississippi = require('./Mississippi_occupation.json');
const Missouri = require('./Missouri_occupation.json');
const Montana = require('./Montana_occupation.json');
const Nebraska = require('./Nebraska_occupation.json');
const Nevada = require('./Nevada_occupation.json');
const New_Hampshire = require('./New_Hampshire_occupation.json');
const New_Jersey = require('./New_Jersey_occupation.json');
const New_Mexico = require('./New_Mexico_occupation.json');
const New_York = require('./New_York_occupation.json');
const North_Carolina = require('./North_Carolina_occupation.json');
const North_Dakota = require('./North_Dakota_occupation.json');
const Ohio = require('./Ohio_occupation.json');
const Oklahoma = require('./Oklahoma_occupation.json');
const Oregon = require('./Oregon_occupation.json');
const Pennsylvania = require('./Pennsylvania_occupation.json');
const Puerto_Rico = require('./Puerto_Rico_occupation.json');
const Rhode_Island = require('./Rhode_Island_occupation.json');
const South_Carolina = require('./South_Carolina_occupation.json');
const South_Dakota = require('./South_Dakota_occupation.json');
const Tennessee = require('./Tennessee_occupation.json');
const Texas = require('./Texas_occupation.json');
const Utah = require('./Utah_occupation.json');
const Vermont = require('./Vermont_occupation.json');
const Virgin_Islands = require('./Virgin_Islands_occupation.json');
const Virginia = require('./Virginia_occupation.json');
const Washington = require('./Washington_occupation.json');
const Washington_DC = require('./Washington_DC_occupation.json');
const West_Virginia = require('./West_Virginia_occupation.json');
const Wisconsin = require('./Wisconsin_occupation.json');
const Wyoming = require('./Wyoming_occupation.json');
const fs = require('fs');

const states = [];
states.push(Alabama);
states.push(Arizona);
states.push(Arkansas);
states.push(Alaska);
states.push(Colorado);
states.push(Connecticut);
states.push(California);
states.push(Delaware);
states.push(District_of_Columbia);
states.push(Florida);
states.push(Georgia);
states.push(Guam);
states.push(Hawaii);
states.push(Idaho);
states.push(Illinois);
states.push(Indiana);
states.push(Iowa);
states.push(Kansas);
states.push(Kentucky);
states.push(Louisiana);
states.push(Maine);
states.push(Maryland);
states.push(Massachusetts);
states.push(Michigan);
states.push(Minnesota);
states.push(Missouri);
states.push(Mississippi);
states.push(Montana);
states.push(Nebraska);
states.push(Nevada);
states.push(New_Hampshire);
states.push(New_Jersey);
states.push(New_Mexico);
states.push(New_York);
states.push(North_Carolina);
states.push(North_Dakota);
states.push(Ohio);
states.push(Oklahoma);
states.push(Oregon);
states.push(Pennsylvania);
states.push(Puerto_Rico);
states.push(Rhode_Island);
states.push(South_Carolina);
states.push(South_Dakota);
states.push(Tennessee);
states.push(Texas);
states.push(Utah);
states.push(Vermont);
states.push(Virgin_Islands);
states.push(Virginia);
states.push(Washington);
states.push(Washington_DC);
states.push(Wisconsin);
states.push(West_Virginia);
states.push(Wyoming);

const result = JSON.stringify(states);

fs.writeFile("../src/datasets/states_occupation.json", result, (err) => {
    if(err)
        console.log(err);
})
